# Generated by Django 3.2.4 on 2021-07-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='author',
        ),
    ]
